version: '3'
services:
  react-frontend:
    build:
      context: ./containers/react-frontend
    ports:
      - "3000:80"
    links:
      - "node-api-server"
  node-api-server:
    build:
      context: ./containers/node-api-server
    expose:
      - "9000"
    ports:
      - "9000:9000"
    links:
      - "mysql"
    environment: 
      - MYSQL_DB_NAME=app
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
  mysql:
    build:
      context: ./containers/mysql
    volumes:
      - ./containers/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./containers/mysql/sqls:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo